services:
  redis-master-1:
    container_name: redis-master-1
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis_conf/redis-master-1.conf:/etc/redis.conf
    restart: always
    ports:
      - 7000:7000
      - 17000:17000
    networks:
      - redis-cluster
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-master-2:
    container_name: redis-master-2
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis_conf/redis-master-2.conf:/etc/redis.conf
    restart: always
    ports:
      - 7001:7001
      - 17001:17001
    networks:
      - redis-cluster
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-master-3:
    container_name: redis-master-3
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis_conf/redis-master-3.conf:/etc/redis.conf
    restart: always
    ports:
      - 7002:7002
      - 17002:17002
    networks:
      - redis-cluster
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-slave-1:
    container_name: redis-slave-1
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis_conf/redis-slave-1.conf:/etc/redis.conf
    restart: always
    ports:
      - 7003:7003
      - 17003:17003
    networks:
      - redis-cluster
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-slave-2:
    container_name: redis-slave-2
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis_conf/redis-slave-2.conf:/etc/redis.conf
    restart: always
    ports:
      - 7004:7004
      - 17004:17004
    networks:
      - redis-cluster
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-slave-3:
    container_name: redis-slave-3
    image: redis
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis_conf/redis-slave-3.conf:/etc/redis.conf
    restart: always
    ports:
      - 7005:7005
      - 17005:17005
    networks:
      - redis-cluster
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-cluster-entry:
    image: redis
    container_name: redis-cluster-entry
    command:
      "
      redis-cli --cluster create redis-master-1:7000 redis-master-2:7001 redis-master-3:7002 redis-slave-1:7003 redis-slave-2:7004 redis-slave-3:7005 --cluster-replicas 1 --cluster-yes
      "
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
