name: CICD

on:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      
      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create application.yml
        run: |
          mkdir -p dateroad-api/src/main/resources
          echo "${{ secrets.CD_APPLICATION }}" > dateroad-api/src/main/resources/application.yml
          cat dateroad-api/src/main/resources/application.yml

          mkdir -p static
          echo "${{ secrets.APPLE_CLIENT_PRIVATE_KEY }}" > static/AuthKey_39CUV6ST46.p8
          cat static/AuthKey_39CUV6ST46.p8
          chmod 400 static/AuthKey_39CUV6ST46.p8
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test --parallel --build-cache --daemon
        working-directory: ${{ env.working-directory }}
        shell: bash

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_LOGIN_ACCESSTOKEN }}

      - name: Docker Image Build and Push
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from dateroad/dateroad-server --platform linux/amd64 -t dateroad/dateroad-server .
          docker push dateroad/dateroad-server
        working-directory: ${{ env.working-directory }}

  cd:
    needs: ci
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~
            ./deploy.sh
            docker image prune -f
